name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Install Eclipse Temurin JDK
        java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v3
      with:
        name: spring-boot-app
        path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download JAR Artifact
      uses: actions/download-artifact@v3
      with:
        name: spring-boot-app

    # Use appleboy/ssh-action to handle SSH-related tasks
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          # Ensure the logs folder exists
          mkdir -p $DEPLOY_PATH/logs;

          # Move the jar file to the deploy path
          mv target/*.jar $DEPLOY_PATH/app.jar;

          # Stop the platform service
          sudo systemctl stop platform.service;

          # Redirect logs to the logs folder
          sudo sed -i '/ExecStart/ c\\ExecStart=/usr/bin/java -jar $DEPLOY_PATH/app.jar >> $DEPLOY_PATH/logs/app.log 2>&1' /etc/systemd/system/platform.service;

          # Reload the systemd configuration to apply changes
          sudo systemctl daemon-reload;

          # Start the platform service
          sudo systemctl start platform.service;
