name: Build and Deploy Platform Service
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build with Maven
      run: mvn clean package -DskipTests
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download JAR
      uses: actions/download-artifact@v3
      with:
        name: app
    - name: Deploy to Server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no *.jar ${SSH_USERNAME}@${SSH_HOST}:${DEPLOY_PATH}/app.jar
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} << EOF
          sudo bash -c 'cat > /etc/systemd/system/platform-service.service << EOL
        [Unit]
        Description=Platform Service
        After=network.target

        [Service]
        User=$SSH_USERNAME
        ExecStart=/usr/bin/java -jar $DEPLOY_PATH/app.jar
        SuccessExitStatus=143
        TimeoutStopSec=10
        Restart=on-failure
        RestartSec=5

        [Install]
        WantedBy=multi-user.target
        EOL'
          sudo systemctl daemon-reload
          sudo systemctl enable platform-service
          sudo systemctl restart platform-service
          echo "Deployment completed"
        EOF