name: Build and Deploy Spring Boot App
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build with Maven
      run: mvn clean package -DskipTests
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download JAR
      uses: actions/download-artifact@v3
      with:
        name: app
    - name: Install sshpass
      run: sudo apt-get install sshpass
    - name: Deploy to Server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no *.jar ${SSH_USERNAME}@${SSH_HOST}:${DEPLOY_PATH}/app.jar
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} '
          mkdir -p ${DEPLOY_PATH}/logs
          if pgrep java; then pkill java; fi
          nohup java -jar ${DEPLOY_PATH}/app.jar > ${DEPLOY_PATH}/logs/app.log 2>&1 &
          echo "Deployment completed"
        '