name: Deploy to EC2
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          mkdir -p ~/.ssh
          mvn clean package -DskipTests

      - name: Create service file
        run: |
          cat << EOF > customer-service.service
          [Unit]
          Description=Customer Service
          After=network.target

          [Service]
          User=matcha
          ExecStart=/usr/bin/java -jar /home/matcha/customer-0.0.1-SNAPSHOT.jar
          EnvironmentFile=/etc/environment
          Restart=always

          [Install]
          WantedBy=multi-user.target
          EOF

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem target/customer-0.0.1-SNAPSHOT.jar matcha@${{ secrets.SSH_HOST }}:~
          scp -o StrictHostKeyChecking=no -i private_key.pem customer-service.service matcha@${{ secrets.SSH_HOST }}:~
          ssh -o StrictHostKeyChecking=no -i private_key.pem matcha@${{ secrets.SSH_HOST }} << 'EOF'
            set -x
            sudo mv ~/customer-service.service /etc/systemd/system/
            sudo systemctl daemon-reload
            sudo systemctl restart customer-service
            sudo systemctl enable customer-service
            sudo systemctl status customer-service
            journalctl -u customer-service -n 20 --no-pager
          EOF
